In [ ]:
import glob #retrieve files/path names matching a specified pattern
from music21 import converter, instrument, note, chord

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!unzip "/content/drive/My Drive/midi_songs.zip" -d "/content/"

unzip:  cannot find or open /content/drive/My Drive/midi_songs.zip, /content/drive/My Drive/midi_songs.zip.zip or /content/drive/My Drive/midi_songs.zip.ZIP.


In [ ]:
notes=[]
for file in glob.glob("/content/midi_songs/*.mid"):
  midi = converter.parse(file) #this will convert the file intp music.21 stream.score objects.
  parts = instrument.partitionByInstrument(midi)# this will create partition into a Part for each unique Instrument.
  notes_to_parse = parts.parts[0]
  #this will have information about the notes,chords and rests in the song.
  #now we need to extract the information of notes and chords.
  for element in notes_to_parse:
    if isinstance(element, note.Note):
      print(str(element.pitch))
      notes.append(str(element.pitch))
    elif isinstance(element, chord.Chord):
      print(str(element.normalOrder))
      notes.append('.'.join(str(n) for n in element.normalOrder))

Streaming output truncated to the last 5000 lines.
E-5
E-3
B-4
G#4
[10, 1]
E4
[3]
[6, 10, 0]
A4
E-3
B-4
[10, 2]
D5
F5
E-3
[11, 2]
D5
[10, 3]
[10, 11, 3, 5]
[0, 3]
E-3
[10, 0, 3]
B4
[10, 3]
[2, 5, 8, 10]
[3, 6]
D5
[10]
[8, 11]
[0, 4]
E-4
[11]
F#4
[10]
[9]
A4
[5]
[4, 10]
[2, 3]
[5]
[2]
[10]
[9]
[2, 8]
[3, 6, 10]
[2, 5, 8]
[6, 10]
[3]
[1]
[11]
F5
[6, 10, 1]
[5, 8, 11]
[3, 6, 10]
[2, 5, 9]
E-5
[4]
B-4
G#4
[1, 6]
[1, 6]
E4
[1, 6]
E-4
F#4
[2, 3]
A4
B-4
D5
[11, 2, 6]
F5
D5
[3, 8]
[3, 6, 10]
[3, 8]
[11]
F#4
[8, 10, 2]
[3, 8]
[10, 3]
G4
[3]
[7]
[11]
[10]
[3]
[7]
[10]
G#5
B-5
[3, 5, 8, 11]
B5
[3, 5, 8, 11]
G#5
B-5
[3, 5, 8, 11]
B5
[3, 5, 8, 11]
G#5
E5
G#5
[3, 5, 8, 11]
B5
B-5
G#5
[3, 5, 8, 11]
F5
G#5
B-5
[3, 5, 8, 11]
B5
[3, 5, 8, 11]
[6, 10]
[5, 9]
F5
B-3
E-4
E-5
C#4
B-4
F#3
F4
E-5
C#4
B-4
C4
F4
E-5
E-3
B-4
B-3
F4
E-5
G#3
B-4
C#3
F4
E-5
F#3
B-4
F3
F4
[10]
[10, 3]
[9, 10]
F6
E-4
B-3
E-6
F3
B-3
E-4
B-3
F#3
[10]
[0, 3]
[10, 2]
[3]
[5, 6]
F#5
E-4
G5
G#5
B-5
[3, 5, 8, 11]
B5
F5
G#6
G#5
B-5
[3, 5, 8,

In [ ]:
notes

['B2',
 'B2',
 'B2',
 'B2',
 'F#2',
 'B2',
 'B2',
 'B2',
 'B2',
 'F#2',
 '9.2',
 'B2',
 '8.1',
 'B2',
 'B2',
 'B2',
 'F#2',
 '9.2',
 'B2',
 '11.4',
 'B2',
 'B2',
 'B2',
 '9.2',
 'F#2',
 'B2',
 '6.11',
 'B2',
 'B2',
 'B2',
 'F#2',
 'B2',
 'B2',
 'B2',
 'B2',
 'F#2',
 '9.2',
 'B2',
 '8.1',
 'B2',
 'B2',
 'B2',
 'F#2',
 '9.2',
 'B2',
 '11.4',
 'B2',
 'B2',
 'B2',
 '1.5',
 'F#2',
 'B2',
 '2.6',
 'B2',
 'B2',
 'B2',
 'F#2',
 'B2',
 'B2',
 'B2',
 'B2',
 'F#2',
 'B2',
 'B2',
 '6.11',
 'B2',
 '1.6',
 '11.2',
 'B2',
 '11.4',
 'A2',
 '1.6',
 '1.6',
 'A2',
 '4.9',
 'A2',
 'A2',
 'E3',
 'E3',
 '1.6',
 'E3',
 '2.7',
 '4.9',
 'E3',
 '6.11',
 'B2',
 '1.4',
 'B2',
 '2',
 'B2',
 'B2',
 'F#2',
 'B2',
 'B2',
 'B2',
 'B2',
 'F#2',
 'B2',
 'B2',
 'B2',
 'B2',
 'F#2',
 'F#2',
 '9.1',
 'F#2',
 '4.9',
 'F#2',
 '2.7',
 'F#2',
 '4.9',
 '6.11',
 'G2',
 '1.4',
 '2.7',
 'G2',
 'B4',
 'G4',
 'G2',
 'F#4',
 'G2',
 'G4',
 'F#2',
 '9.1',
 'F#2',
 '4.9',
 'F#2',
 '2.6',
 'F#2',
 '4.7',
 '6.9',
 'E3',
 '4.9',
 '11.2',
 

In [ ]:
len(notes)

57177

In [ ]:
import numpy 
from keras.utils import np_utils

n_vocab = len(set(notes))#to get the number of unique data present in notes
sequence_length = 100  #You can keep it higher or lower
print(n_vocab)

# get all pitch names
pitchnames = sorted(set(item for item in notes)) #getting various unique data present in notes
# create a dictionary to map pitches to integers
note_to_int = dict((note, number) for number, note in enumerate(pitchnames))
print(note_to_int)

network_input = []
network_output = []
# create input sequences and the corresponding outputs
for i in range(0, len(notes) - sequence_length):
    sequence_in = notes[i:i + sequence_length]
    sequence_out = notes[i + sequence_length]
    network_input.append([note_to_int[char] for char in sequence_in])
    network_output.append(note_to_int[sequence_out])


358
{'0': 0, '0.1': 1, '0.1.5': 2, '0.1.6': 3, '0.2': 4, '0.2.3.7': 5, '0.2.4.7': 6, '0.2.5': 7, '0.2.6': 8, '0.2.7': 9, '0.3': 10, '0.3.5': 11, '0.3.5.8': 12, '0.3.6': 13, '0.3.6.8': 14, '0.3.6.9': 15, '0.3.7': 16, '0.4': 17, '0.4.5': 18, '0.4.6': 19, '0.4.7': 20, '0.5': 21, '0.5.6': 22, '0.6': 23, '1': 24, '1.2': 25, '1.2.4.6.8.10': 26, '1.2.6': 27, '1.2.6.8': 28, '1.3': 29, '1.3.5': 30, '1.3.5.8': 31, '1.3.6': 32, '1.3.7': 33, '1.3.8': 34, '1.4': 35, '1.4.6': 36, '1.4.6.9': 37, '1.4.7': 38, '1.4.7.10': 39, '1.4.7.9': 40, '1.4.8': 41, '1.5': 42, '1.5.8': 43, '1.5.9': 44, '1.6': 45, '1.7': 46, '10': 47, '10.0': 48, '10.0.2.5': 49, '10.0.3': 50, '10.0.4': 51, '10.0.5': 52, '10.1': 53, '10.1.3': 54, '10.1.3.5.6': 55, '10.1.3.6': 56, '10.1.4': 57, '10.1.4.6': 58, '10.1.5': 59, '10.11': 60, '10.11.3': 61, '10.11.3.5': 62, '10.2': 63, '10.2.3': 64, '10.2.4': 65, '10.2.5': 66, '10.3': 67, '11': 68, '11.0': 69, '11.0.4': 70, '11.0.4.6': 71, '11.0.4.7': 72, '11.0.5': 73, '11.1': 74, '11.1.4':

In [ ]:
len(pitchnames)

358

In [ ]:
n_patterns = len(network_input)
print(n_patterns)
# reshape the input into a format compatible with LSTM layers
network_input = numpy.reshape(network_input, (n_patterns, sequence_length, 1))
#normalize input
network_input = network_input / float(n_vocab)
network_output = np_utils.to_categorical(network_output)

57077


In [ ]:
print(network_input.shape)

(57077, 100, 1)


In [ ]:
print(network_input)

[[[0.82681564]
  [0.82681564]
  [0.82681564]
  ...
  [0.82681564]
  [0.82681564]
  [0.82681564]]

 [[0.82681564]
  [0.82681564]
  [0.82681564]
  ...
  [0.82681564]
  [0.82681564]
  [0.82681564]]

 [[0.82681564]
  [0.82681564]
  [0.93575419]
  ...
  [0.82681564]
  [0.82681564]
  [0.93575419]]

 ...

 [[0.81284916]
  [0.55586592]
  [0.97486034]
  ...
  [0.84636872]
  [0.83240223]
  [0.92458101]]

 [[0.55586592]
  [0.97486034]
  [0.24860335]
  ...
  [0.83240223]
  [0.92458101]
  [0.92178771]]

 [[0.97486034]
  [0.24860335]
  [0.95810056]
  ...
  [0.92458101]
  [0.92178771]
  [0.90502793]]]


In [ ]:
network_output[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
len(network_output[0])

358

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.layers import Activation

In [ ]:
model = Sequential()
model.add(LSTM(
        256,
        input_shape=(network_input.shape[1], network_input.shape[2]),
        return_sequences=True
    ))
model.add(Dropout(0.3))
model.add(LSTM(512, return_sequences=True))
model.add(Dropout(0.3))
model.add(LSTM(256))
model.add(Dense(256))
model.add(Dropout(0.3))
model.add(Dense(n_vocab))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 100, 256)          264192    
_________________________________________________________________
dropout (Dropout)            (None, 100, 256)          0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 100, 512)          1574912   
_________________________________________________________________
dropout_1 (Dropout)          (None, 100, 512)          0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 256)               787456    
_________________________________________________________________
dense (Dense)                (None, 256)               65792     
_________________________________________________________________
dropout_2 (Dropout)          (None, 256)               0

In [ ]:
model.fit(network_input, network_output, epochs=80, batch_size=32)

Epoch 1/80
  14/1784 [..............................] - ETA: 1:22:47 - loss: 5.6343

KeyboardInterrupt: ignored

In [ ]:
from keras.models import load_model
from keras.models import model_from_json

In [ ]:
# Model reconstruction from JSON file
with open('/content/music.json', 'r') as f:
    model = model_from_json(f.read())

In [ ]:
model.load_weights('/content/music125.h5')

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 100, 256)          264192    
_________________________________________________________________
dropout_3 (Dropout)          (None, 100, 256)          0         
_________________________________________________________________
lstm_4 (LSTM)                (None, 100, 512)          1574912   
_________________________________________________________________
dropout_4 (Dropout)          (None, 100, 512)          0         
_________________________________________________________________
lstm_5 (LSTM)                (None, 256)               787456    
_________________________________________________________________
dense_2 (Dense)              (None, 256)               65792     
_________________________________________________________________
dropout_5 (Dropout)          (None, 256)              

In [ ]:
import numpy
start = numpy.random.randint(0, len(network_input)-1)
int_to_note = dict((number, note) for number, note in enumerate(pitchnames))
pattern = (network_input[start])
prediction_output = []
# generate 500 notes
for note_index in range(500):
    prediction_input = numpy.reshape(pattern, (1, len(pattern), 1))
    prediction_input = (prediction_input) / float(n_vocab)
    prediction = model.predict(prediction_input, verbose=0)
    index = numpy.argmax(prediction)
    result = int_to_note[index]
    prediction_output.append(result)
    pattern=numpy.append(pattern,index)
    pattern = pattern[1:len(pattern)]

In [ ]:
prediction_output

['0.5',
 '0.5',
 '0.5',
 '0.5',
 '0.5',
 '0.5',
 '0.5',
 '0.5',
 '0.5',
 '0.5',
 '0.5',
 '0.5',
 '0.5',
 '2.5',
 '0.5',
 '0.5',
 '0.5',
 '0.5',
 '2.5',
 '0.5',
 '0.5',
 '0.5',
 '0.5',
 '2.5',
 '2.5',
 '0.5',
 '0.5',
 '0.5',
 '0.5',
 '2.5',
 '0.5',
 '2.5',
 '0.5',
 '0.5',
 '0.5',
 '2.5',
 '0.5',
 '2.5',
 '0.5',
 '0.5',
 '0.5',
 '2.5',
 '0.5',
 '2.5',
 '0.5',
 '0.5',
 '2.5',
 '2.5',
 '0.5',
 '5.10',
 '0.5',
 '0.5',
 '0.5',
 '2.5',
 '0.5',
 '2.5',
 '0.5',
 '0.5',
 '2.5',
 '2.5',
 '0.5',
 '5.10',
 '0.5',
 '0.5',
 '0.5',
 '2.5',
 '2.5',
 '2.5',
 '0.5',
 '0.5',
 '0.5',
 '0.5',
 '2.5',
 '0.5',
 '2.5',
 '0.5',
 '0.5',
 '2.5',
 '2.5',
 '0.5',
 '0.5',
 '0.5',
 '2.5',
 '0.5',
 '2.5',
 '0.5',
 '0.5',
 '2.5',
 '2.5',
 '0.5',
 '0.5',
 '0.5',
 '2.5',
 '0.5',
 '2.5',
 '0.5',
 '0.5',
 '2.5',
 '2.5',
 '0.5',
 '0.5',
 '0.5',
 '2.5',
 '0.5',
 '2.5',
 '0.5',
 '0.5',
 '2.5',
 '2.5',
 '0.5',
 '0.5',
 '0.5',
 '2.5',
 '0.5',
 '2.5',
 '0.5',
 '0.5',
 '2.5',
 '2.5',
 '0.5',
 '0.5',
 '0.5',
 '2.5',
 '0.5',
 '2.5'

In [ ]:
len(prediction_output)

500

In [ ]:
offset = 0
output_notes = []
# create note and chord objects based on the values generated by the model
for pattern in prediction_output:
    # pattern is a chord
    if ('.' in pattern) or pattern.isdigit():
        notes_in_chord = pattern.split('.')
        notes = []
        for current_note in notes_in_chord:
            new_note = note.Note(int(current_note))
            new_note.storedInstrument = instrument.Piano()
            notes.append(new_note)
        new_chord = chord.Chord(notes)
        new_chord.offset = offset
        output_notes.append(new_chord)
    # pattern is a note
    else:
        new_note = note.Note(pattern)
        new_note.offset = offset
        new_note.storedInstrument = instrument.Piano()
        output_notes.append(new_note)
    # increase offset each iteration so that notes do not stack
    offset += 1.5

In [ ]:
import music21
midi_stream = music21.stream.Stream(output_notes)
midi_stream.write('midi', fp='test_output_try2.mid')

'test_output_try2.mid'